name: 'Runtime checks'
description: 'Run dynamic analysis tools'

runs:
  using: "composite"
  steps:
    - name: Sanitizers
      shell: bash
      # Rulam pe Linux si macOS (excluzand Windows)
      if: matrix.runs_asan == true && runner.os != 'Windows'
      run: |
        if [[ "${RUNNER_OS}" == "Linux" ]]; then
          # Pe Linux headless simulam un ecran virtual in memorie cu xvfb-run
          xvfb-run cat "${INPUT_FILENAME}" | tr -d '\r' | ./${{ env.ZIP_NAME }}/"${EXECUTABLE_NAME}"
        else
          # Pe macOS nu este nevoie de ecran virtual dedicat in CI
          cat "${INPUT_FILENAME}" | tr -d '\r' | ./${{ env.ZIP_NAME }}/"${EXECUTABLE_NAME}"
        fi

    - name: Sanitizers (Windows MSVC)
      shell: bash
      if: matrix.cxx == 'cl' && matrix.runs_asan == true
      continue-on-error: true
      run: |
        cat "${INPUT_FILENAME}" | ./${{ env.ZIP_NAME }}/"${EXECUTABLE_NAME}".exe

    - name: Valgrind
      shell: bash
      if: runner.os == 'Linux' && matrix.runs_valgrind == true
      run: |
        # Invelim si rularea de Valgrind in xvfb-run pentru a evita crash-ul de display pe Linux
        xvfb-run bash ./scripts/run_valgrind.sh "${{ env.ZIP_NAME }}"